### ISSUE TITLE
Work Folders - There was a problem finding your Work Folders Server

### ISSUE THREAD

**Issue by Miller6025** [MicrosoftLearning/MD-100T00-Windows10#15]
# Module: 08
#### Step: 00

Description of issue"
Logged in as Lon-cl3/admin
Control Panel > Sytem and Security > Work folders
Setup UP Work folders
Enter URL of Work Folder URL:  https://lon-dc1.adatum.com
ERROR MESSAGE:  There was a problem finding your Work Folders Server
Repeated with user account lon-cl3/student - still failed
Repro steps:

1. Ping Lon-DC1 - success
2.On Lon-DC1, verified Windows Sync Share is running
3. On Lon-DC1, AD running, DNS Running
4.  Event Viewer > Applications & Services > Microsoft > WIndows > SyncShare > Operational
  ERROR:  No Sync Share is configured for the user Administrator.
 WARNING:  There was a problem retrieving a user attribute from Active Directory Domain Services. 
 INFORMATION:  The Windows Sync Share Services successfully setup
5.  Verified that IIS is running and that the Default Web Site is running with the 443/digital certificate as described in lab steps
6.  On Lon-Cl3, open I.E. and enter https://lon-dc1.adatum.com - page loads successfully.
7.  Rebooted Lon-Dc1, did not solve issue
8.  Removed Sync Share and recreated, same issue

**Comment by BrianHinkelman** [comment]
Thanks for reporting this - we are investigating the issue.

**Comment by BrianHinkelman** [comment]
Closed per Feb 2021 update
