### ISSUE TITLE
Lab 0202-Using Settings App & Control Panel, Task 1, Step 8:  Missing Folder

### ISSUE THREAD

**Issue by Bobkr01** [MicrosoftLearning/MD-100T00-Windows10#18]
# Module: 00
#### Step: 00

Description of issue
Lab 0202-Using Settings App & Control Panel, Task 1, Step 8:  C:\Util folder does not exist
Repro steps:
Lab 0202-Using Settings App & Control Panel
Task 1: Using the Settings Apps
Step 8:  Browse to C:\UTIL and select Select Folder. In the User Account Control window select Yes

ISSUE:  C:\UTIL folder does not exist on LON-CL3 and there is no guidance to create it.  Some students working 'self-paced' in class stopping/getting stuck, not sure what they should do.
1.
1.
1.

**Comment by BrianHinkelman** [comment]
The VMs included for MD-100 do have a C:\UTIL folder on LON-CL3.  Please contact the ALH and verify you have been provisioned the correct VMs (and the correct version - MD100T00A).
