### ISSUE TITLE
Security cert expired 12/30/2020

### ISSUE THREAD

**Issue by LodsCory** [MicrosoftLearning/MD-100T00-Windows10#19]
# Module: 00
#### Step: 04

Description of issue
Security cert expired on 12/30/2020 preventing the completion of the task.

![image](https://user-images.githubusercontent.com/62734074/103404844-07b25b80-4b23-11eb-8033-7875be5c471f.png)

Repro steps:

1. go to lab 0601: sideloading an app and follow instructions to task 3 step 4.
1.
1.

**Comment by BrianHinkelman** [comment]
Thanks for reporting this.   We are currently working to deliver new labs in February, which will have refreshed VMs. I will note that this particular lab is being retired.  There will not be a sideloading lab in the next update.
