### ISSUE TITLE
Allfiles TestAppTKL1 certificate is expired

### ISSUE THREAD

**Issue by zapppy69** [MicrosoftLearning/MD-100T00-Windows10#23]
I need a fresh cert LexProductsGrid81_AnyCPU.cer ASAP. That would be really helpful as 100 students are on hold because of this. Thanks

**Comment by DaleMcC** [comment]
That cert will not be updated. That entire lab has been removed in the lab refresh that happened last Friday.

**Comment by BrianHinkelman** [comment]
Correct, the lab that used the certificate has been retired. This lab should no longer be available. If you are still being provisioned an environment that has this lab (Sideloading an App), please contact your Authorized Lab Host.
