### ISSUE TITLE
managing Windows Settings Module 3 lab lab 0301

### ISSUE THREAD

**Issue by edbakermct** [MicrosoftLearning/MD-100T00-Windows10#26]
# Module: 00
#### Step: 00

lab0301 throughout the instructions
There a SIX (6) instances of instructions directing the student to use c:\labfiles on SEA-CL1

BUT SEA-CL1 has its labfiles in the e: drive....

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Repro steps:

1.
1.
1.

**Comment by BrianHinkelman** [comment]
Thanks, will update.
