### ISSUE TITLE
1202 Recovering Windows using Reset this PC

### ISSUE THREAD

**Issue by directorofeducation** [MicrosoftLearning/MD-100T00-Windows10#28]
# Module: 1202
#### Step: 12

There is a "How would you like to reinstall Windows?" screen and an "Additional settings" screen after you click Keep my files in Step 11.

![How would you like to reinstall](https://user-images.githubusercontent.com/66324487/110715533-45ce9a00-81ba-11eb-84a5-83bdae40b9cd.png)
![Additional settings](https://user-images.githubusercontent.com/66324487/110715535-47985d80-81ba-11eb-8c24-2064b53f92f7.png)

**Comment by AustinP00** [comment]
can confirm by selecting local reinstall and than next on the additional settings tab allows us to complete this section of the lab properly. 

adding alert prior to section to state these two additional steps.

**Comment by BrianHinkelman** [comment]
Thanks for catching this, will add step.
