### ISSUE TITLE
0301 Managing Windows 10 Settings

### ISSUE THREAD

**Issue by directorofeducation** [MicrosoftLearning/MD-100T00-Windows10#32]
# Module: 03
## Lab/Demo: 01
###Exercise: 03
##### Step: 05

This step is missing the closing angle bracket.
At the first instance of <DefaultLayoutOverride>, type the following:
<DefaultLayoutOverride LayoutCustomizationRestrictionType="OnlySpecifiedGroups"

**Comment by BrianHinkelman** [comment]
Thanks, will update
