### ISSUE TITLE
1002-Monitoring Reliability and Performance

### ISSUE THREAD

**Issue by directorofeducation** [MicrosoftLearning/MD-100T00-Windows10#41]
# Module: 10
#### Step: 04

The CopyMonitor.bat on DC1 copies the MonitorScenario file to C:\Monitor. The command in step 4 fails as it cannot find the file. The command should say:
cd C:\Monitor MonitorScenario.vbs

**Comment by BrianHinkelman** [comment]
Unable to repro, tested steps as written, closing.
