### ISSUE TITLE
Microsoft Store Update switch is grayed out and off

### ISSUE THREAD

**Issue by joel-berk** [MicrosoftLearning/MD-100T00-Windows10#42]
# Module: 08
#### Step: 02

Description of issue
In the Microsoft Store, under settings, under App updates, the switch called "Update apps automatically" is grayed out and in the off position. Was that the intended result? Note: The lab works with the switch in the off (disabled) position. Otherwise, the registry key HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\WindowsStore, AutoDownload setting can be modified to 4 to set it on (enabled) but still grayed out. Also, This is where the GPO is set to gray it out: 
1. Open gpedit.msc
2. Under Computer Configuration // Administrative Templates // Store 
3. Select Turn off Automatic Download  of Updates on Win8 Machines - Select Enable or not configured ( note that not configured will depend on what has already been set on the registry)
Thank you.
Repro steps:

1.
1.
1.

**Comment by BrianHinkelman** [comment]
This is likely configured by the ALH to prevent devices from automatically updated. It should not impact the lab, will update steps - thanks.
