### ISSUE TITLE
0801-Installing Apps in Windows 10

### ISSUE THREAD

**Issue by davemct** [MicrosoftLearning/MD-100T00-Windows10#56]
# Module: 08
#### Step: 01

Description of issue

The step says to select the **See more** ellipses on the menu bar, and then select **Settings**.

The entire Microsoft Store UI has changed.  The menu bar has been moved from the top to the side and there is no longer any **See more** ellipses.  Steps need to be updated/added to complete this lab.

Repro steps:

1.
1.
1.

**Comment by davemct** [comment]
The Microsoft Store user interface hasn't changed in a long while.  Now it has.  Other courses' labs need to be updated/fixed also.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review has resolved this issue with pull request #61
