### ISSUE TITLE
0901 - Configuring Microsoft Defender Antivirus and Windows Security

### ISSUE THREAD

**Issue by directorofeducation** [MicrosoftLearning/MD-100T00-Windows10#57]
# Module: 09
#### Step: 08

In Exercise 1, Task 3, Step 8 the lab mentions deleting instances of text within brackets <> however the instructions no longer mention which item to delete.

![image](https://user-images.githubusercontent.com/66324487/148831635-e9a502fb-a511-46be-847a-6aa36920ee30.png)

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review has solved this issue with pull request #62
