### ISSUE TITLE
MD-100 Lab1: Issue Dism command?!?

### ISSUE THREAD

**Issue by Potse** [MicrosoftLearning/MD-100T00-Windows10#65]
In the first Practice Lab: "Deploying Windows using Windows ADK Tools", Task 5: Deploy a Captured Windows 10 Image, step 19: At the command prompt type the following command to apply the gold image to Computer1: Dism /apply-image /imagefile:Z:\GoldImage.wim /index:1 /ApplyDir:G:\ I get the following: "error: 13 The data is invalid" and a reference to 
the DISM Log on drive X. 
However I can't make anything of that. I did the practice lab twice with different lab hosters with an equal result. Of course it's possible that 
I'm doing something wrong, but I worked very precisely both times.

**Comment by ITBlandMCT** [comment]
@Potse if you are using hosted labs and you use the "paste it for me" buttons, the pasted command will often not type properly. (Very often ":" will be replaced with ";" and capital letters will type as lower-case.) 
**Verify** carefully all "typed" commands in **Task 4: Capture a reference Windows 10 image** and **Task 5: Deploy a captured Windows 10 image** and be sure the capture-image in Task 4 _has completed successfully_ before running apply-image in Task 5.
As always, if you are a student taking this class, please ask your trainer for help.

**Comment by BrianHinkelman** [comment]
This lab was just recently tested and they were unable to repro the error. Given others are not having the issue, recommend ITBlandMCT's suggestion. If that does remedy the issue, please notify the ALH.
