### ISSUE TITLE
0601-Configuring and Managing Local and Share Permissions

### ISSUE THREAD

**Issue by WigF1** [MicrosoftLearning/MD-100T00-Windows10#75]
# Module: 06
#### Step: 04

Description of issue

Step 3 instructs students to select AllFiles (D:), which is correct. 

Step 4 instructs students to select AllFiles (E:), which is ***not*** correct.

Both should refer to AllFiles (D:)

![image](https://user-images.githubusercontent.com/12164329/181182767-c17911de-123a-4a89-8817-b3eeb70f6849.png)

**Comment by MSFT-rstearman** [comment]
This issue has been resolved.
