### ISSUE TITLE
0604-Synchronizing Files with OneDrive

### ISSUE THREAD

**Issue by WigF1** [MicrosoftLearning/MD-100T00-Windows10#76]
# Module: 06
#### Step: 01

Description of issue

Students should be instructed to sign-in to SEA-WS1 as .\\Student

**Comment by MSFT-rstearman** [comment]
Can't recreate this issue.

**Comment by WigF1** [comment]
Whether you could or not, the issue remains. See #81 raised by @craigbeeremct
