### ISSUE TITLE
0103-Migrating user state using USMT

### ISSUE THREAD

**Issue by jubic** [MicrosoftLearning/MD-100T00-Windows10#83]
# Module: 01
#### Step: 10

Description of issue

`Loadstate \\SEA-SVR2\Labfiles\Install\MigrationStore\Win10 /i:migapp.xml /i:miguser.xml /lac:Pa55w.rd /lae /c`

should be replaced by

`Loadstate \\SEA-SVR2\Labfiles\Install\MigrationStore\Win10 /i:migapp.xml /i:miguser.xml /lac:Pa55w.rd1234 /lae /c`

Otherwise it will return "Password must meet complexity requirements"

**Comment by MSFT-rstearman** [comment]
Can't recreate this issue.
